### Get Users
GET http://localhost:8080/v1/user?createdAt=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVdWlkIjoiNjViZGJiZDYtNjZlOS00Nzc4LTg1ODgtZDU1ZTUxMDhiYzBhIiwiUm9sZSI6Iml0IiwiaXNzIjoiaGFsb3N1c3RlciIsInN1YiI6IlJhdGloIEluZGFoIiwiZXhwIjoxNzE2MDcwNDM4LCJpYXQiOjE3MTYwNDE2MzgsImp0aSI6IjY1YmRiYmQ2LTY2ZTktNDc3OC04NTg4LWQ1NWU1MTA4YmMwYSJ9.DRM_Be99P0QiOPliraNlrZG_tnyPcS3YR9hl7J0SsYY