version: "3.8"
services:
  db:
    container_name: "testing"
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=testing
volumes:
  pgdata:
